theme = "gruvbox_dark_hard"

[editor.cursor-shape]
insert = "bar"

[editor]
line-number ="relative"
mouse = false
bufferline = "multiple"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-p = ":clipboard-paste-replace"
C-x = ":bc"
C-v = ":clipboard-paste-after"
